---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-sidecar
data:
  VAULT_ADDR: https://vault.addr
  VAULT_AUTH_PROVIDER: vault-provider
  VAULT_AUTH_ROLE: iam-role
  VAULT_IS_STUB: "no"
  kv-data.json: |
    {
      "API_TOKEN": "vault-mount/app/token2",
      "DB_PASSWORD": "vault-mount/app/db/password2"
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-sidecar
  template:
    metadata:
      labels:
        app: vault-sidecar
    spec:
      containers:
        - name: primary-app
          image: yamaszone/curl:latest
          imagePullPolicy: Always
          command:
            - "sh"
            - "-c"
            - >
              while true; do
                sleep 3600
              done
          volumeMounts:
            - name: vault-sidecar
              mountPath: /etc/vault
        - name: vault-sidecar
          image: yamaszone/vault-proxy:latest
          imagePullPolicy: Always
          env:
            - name: VAULT_ADDR
              valueFrom:
                configMapKeyRef:
                  name: vault-sidecar
                  key: VAULT_ADDR
            - name: VAULT_AUTH_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: vault-sidecar
                  key: VAULT_AUTH_PROVIDER
            - name: VAULT_AUTH_ROLE
              valueFrom:
                configMapKeyRef:
                  name: vault-sidecar
                  key: VAULT_AUTH_ROLE
            - name: VAULT_IS_STUB
              valueFrom:
                configMapKeyRef:
                  name: vault-sidecar
                  key: VAULT_IS_STUB
          volumeMounts:
            - name: vault-sidecar
              mountPath: /etc/vault

      volumes:
        - name: vault-sidecar
          configMap:
            name: vault-sidecar
            items:
            - key: kv-data.json
              path: kv-data.json
