// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Vault Secrets Proxy Sidecar

    Schemes:
      http
    Host: localhost
    BasePath: /v1
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json
    - text/plain

swagger:meta
*/
package restapi
